ALTER TYPE "TenantStatus" ADD VALUE IF NOT EXISTS 'DEMO';

ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "kycStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "taxExempt" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "taxExemptionCertificateUrl" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "crmDealId" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "demoExpiresAt" TIMESTAMP(3);

CREATE TABLE "dunning_sequences" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "steps" JSONB NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "dunning_sequences_pkey" PRIMARY KEY ("id"));
CREATE TABLE "dunning_steps" ("id" TEXT NOT NULL, "sequenceId" TEXT NOT NULL, "dayOffset" INTEGER NOT NULL, "action" TEXT NOT NULL, "template" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "dunning_steps_pkey" PRIMARY KEY ("id"));
CREATE TABLE "dunning_events" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "invoiceId" TEXT, "eventType" TEXT NOT NULL, "attempt" INTEGER NOT NULL DEFAULT 0, "metadata" JSONB, "actorId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "dunning_events_pkey" PRIMARY KEY ("id"));
CREATE TABLE "save_offers" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "discount" DECIMAL(12,2) NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "approvedBy" TEXT, "reason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "save_offers_pkey" PRIMARY KEY ("id"));

CREATE TABLE "incident_records" ("id" TEXT NOT NULL, "vendor" TEXT NOT NULL DEFAULT 'pagerduty', "vendorId" TEXT NOT NULL, "title" TEXT NOT NULL, "status" TEXT NOT NULL, "severity" TEXT, "serviceTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "postmortemUrl" TEXT, "payload" JSONB, "startedAt" TIMESTAMP(3), "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "incident_records_pkey" PRIMARY KEY ("id"));
CREATE TABLE "incident_tenant_impacts" ("id" TEXT NOT NULL, "incidentId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "impactLevel" TEXT NOT NULL DEFAULT 'UNKNOWN', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "incident_tenant_impacts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "incident_runbooks" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "body" TEXT NOT NULL, "service" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "incident_runbooks_pkey" PRIMARY KEY ("id"));

CREATE TABLE "support_vendor_tickets" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "vendor" TEXT NOT NULL DEFAULT 'zendesk', "vendorId" TEXT NOT NULL, "subject" TEXT NOT NULL, "status" TEXT NOT NULL, "priority" TEXT, "url" TEXT, "requesterEmail" TEXT, "latestMessage" TEXT, "sentiment" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "support_vendor_tickets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "tenant_health_scores" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "score" INTEGER NOT NULL, "trend" TEXT NOT NULL DEFAULT 'flat', "factors" JSONB NOT NULL, "computedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "tenant_health_scores_pkey" PRIMARY KEY ("id"));
CREATE TABLE "cs_playbooks" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "trigger" TEXT NOT NULL, "steps" JSONB NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "cs_playbooks_pkey" PRIMARY KEY ("id"));
CREATE TABLE "cs_playbook_runs" ("id" TEXT NOT NULL, "playbookId" TEXT, "tenantId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "steps" JSONB NOT NULL, "currentStep" INTEGER NOT NULL DEFAULT 0, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "cs_playbook_runs_pkey" PRIMARY KEY ("id"));

CREATE TABLE "jit_access_requests" ("id" TEXT NOT NULL, "requesterPlatformUserId" TEXT NOT NULL, "requesterStaffId" TEXT, "permission" TEXT NOT NULL, "reason" TEXT NOT NULL, "durationMinutes" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "rootRequest" BOOLEAN NOT NULL DEFAULT false, "hardwareKeyVerified" BOOLEAN NOT NULL DEFAULT false, "expiresAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "deniedReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "jit_access_requests_pkey" PRIMARY KEY ("id"));
CREATE TABLE "jit_access_approvals" ("id" TEXT NOT NULL, "requestId" TEXT NOT NULL, "approverPlatformUserId" TEXT NOT NULL, "decision" TEXT NOT NULL, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "jit_access_approvals_pkey" PRIMARY KEY ("id"));

CREATE TABLE "dsar_requests" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "requesterEmail" TEXT NOT NULL, "requestType" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'RECEIVED', "notes" TEXT, "exportUrl" TEXT, "expiresAt" TIMESTAMP(3), "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dueAt" TIMESTAMP(3) NOT NULL, "closedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "dsar_requests_pkey" PRIMARY KEY ("id"));
CREATE TABLE "dsar_transitions" ("id" TEXT NOT NULL, "dsarId" TEXT NOT NULL, "fromStatus" TEXT, "toStatus" TEXT NOT NULL, "actorId" TEXT NOT NULL, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "dsar_transitions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "legal_holds" ("id" TEXT NOT NULL, "tenantId" TEXT, "scope" JSONB NOT NULL, "reason" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdBy" TEXT NOT NULL, "releasedBy" TEXT, "releasedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "legal_holds_pkey" PRIMARY KEY ("id"));
CREATE TABLE "compliance_exports" ("id" TEXT NOT NULL, "tenantId" TEXT, "dsarId" TEXT, "exportType" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "s3Key" TEXT, "signedUrl" TEXT, "expiresAt" TIMESTAMP(3), "requestedBy" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "compliance_exports_pkey" PRIMARY KEY ("id"));

CREATE TABLE "fraud_signals" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "source" TEXT NOT NULL, "signalType" TEXT NOT NULL, "severity" TEXT NOT NULL DEFAULT 'MEDIUM', "status" TEXT NOT NULL DEFAULT 'OPEN', "payload" JSONB, "reviewedBy" TEXT, "decision" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "fraud_signals_pkey" PRIMARY KEY ("id"));
CREATE TABLE "suspension_records" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "reason" TEXT NOT NULL, "sourceSignalId" TEXT, "suspendedBy" TEXT NOT NULL, "liftedBy" TEXT, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "liftedAt" TIMESTAMP(3), CONSTRAINT "suspension_records_pkey" PRIMARY KEY ("id"));
CREATE TABLE "tenant_appeals" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "suspensionId" TEXT, "message" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "resolvedBy" TEXT, "resolution" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "tenant_appeals_pkey" PRIMARY KEY ("id"));

CREATE TABLE "feature_flag_override_audits" ("id" TEXT NOT NULL, "flagKey" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "value" JSONB NOT NULL, "actorId" TEXT NOT NULL, "vendor" TEXT NOT NULL DEFAULT 'launchdarkly', "vendorRef" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "feature_flag_override_audits_pkey" PRIMARY KEY ("id"));
CREATE TABLE "secret_credentials" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "dopplerId" TEXT, "provider" TEXT NOT NULL DEFAULT 'doppler', "ownerId" TEXT, "expiresAt" TIMESTAMP(3), "rotationNotes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "secret_credentials_pkey" PRIMARY KEY ("id"));
CREATE TABLE "secret_access_logs" ("id" TEXT NOT NULL, "secretId" TEXT NOT NULL, "accessedBy" TEXT NOT NULL, "source" TEXT NOT NULL, "justification" TEXT, "accessedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "secret_access_logs_pkey" PRIMARY KEY ("id"));

CREATE TABLE "staff_login_attempts" ("id" TEXT NOT NULL, "staffEmail" TEXT NOT NULL, "platformUserId" TEXT, "success" BOOLEAN NOT NULL, "ipAddress" TEXT, "country" TEXT, "userAgent" TEXT, "failureReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "staff_login_attempts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "security_anomalies" ("id" TEXT NOT NULL, "anomalyType" TEXT NOT NULL, "severity" TEXT NOT NULL DEFAULT 'MEDIUM', "actorId" TEXT, "tenantId" TEXT, "status" TEXT NOT NULL DEFAULT 'OPEN', "payload" JSONB, "resolvedBy" TEXT, "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "security_anomalies_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ip_blocks" ("id" TEXT NOT NULL, "ipAddress" TEXT NOT NULL, "reason" TEXT NOT NULL, "expiresAt" TIMESTAMP(3), "createdBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ip_blocks_pkey" PRIMARY KEY ("id"));

CREATE TABLE "kyc_reviews" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "provider" TEXT NOT NULL DEFAULT 'persona', "inquiryId" TEXT, "status" TEXT NOT NULL DEFAULT 'PENDING', "decision" TEXT, "documentS3Key" TEXT, "payload" JSONB, "reviewedBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "kyc_reviews_pkey" PRIMARY KEY ("id"));
CREATE TABLE "sanctions_screenings" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "provider" TEXT NOT NULL DEFAULT 'complyadvantage', "status" TEXT NOT NULL DEFAULT 'PENDING', "matchType" TEXT, "riskLevel" TEXT, "payload" JSONB, "reviewedBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "sanctions_screenings_pkey" PRIMARY KEY ("id"));

CREATE TABLE "integration_provider_statuses" ("id" TEXT NOT NULL, "provider" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'UNKNOWN', "lastSuccessfulAt" TIMESTAMP(3), "errorRate24h" DECIMAL(8,4) NOT NULL DEFAULT 0, "payload" JSONB, "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "integration_provider_statuses_pkey" PRIMARY KEY ("id"));
CREATE TABLE "tax_registrations" ("id" TEXT NOT NULL, "region" TEXT NOT NULL, "taxId" TEXT NOT NULL, "filingFrequency" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "tax_registrations_pkey" PRIMARY KEY ("id"));
CREATE TABLE "tax_returns" ("id" TEXT NOT NULL, "region" TEXT NOT NULL, "periodStart" TIMESTAMP(3) NOT NULL, "periodEnd" TIMESTAMP(3) NOT NULL, "taxCollected" DECIMAL(12,2) NOT NULL DEFAULT 0, "taxPaidOut" DECIMAL(12,2) NOT NULL DEFAULT 0, "netDue" DECIMAL(12,2) NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'PENDING', "exportUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "tax_returns_pkey" PRIMARY KEY ("id"));
CREATE TABLE "tax_exemptions" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "certificateUrl" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "approvedBy" TEXT, "approvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "tax_exemptions_pkey" PRIMARY KEY ("id"));

CREATE TABLE "custom_contracts" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "msaUrl" TEXT, "termStart" TIMESTAMP(3) NOT NULL, "termEnd" TIMESTAMP(3) NOT NULL, "terms" JSONB NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "signedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "custom_contracts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "pricing_overrides" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "contractId" TEXT, "ruleType" TEXT NOT NULL, "ruleValue" JSONB NOT NULL, "discountPercent" DECIMAL(6,2), "validFrom" TIMESTAMP(3) NOT NULL, "validTo" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "pricing_overrides_pkey" PRIMARY KEY ("id"));
CREATE TABLE "contract_approvals" ("id" TEXT NOT NULL, "contractId" TEXT NOT NULL, "approverId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "conditions" TEXT, "approvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "contract_approvals_pkey" PRIMARY KEY ("id"));
CREATE TABLE "sales_quotes" ("id" TEXT NOT NULL, "tenantId" TEXT, "dealId" TEXT, "quoteNumber" TEXT NOT NULL, "plan" TEXT NOT NULL, "termMonths" INTEGER NOT NULL, "discountPercent" DECIMAL(6,2) NOT NULL DEFAULT 0, "customFeatures" JSONB, "status" TEXT NOT NULL DEFAULT 'DRAFT', "docusignEnvelopeId" TEXT, "signedPdfS3Key" TEXT, "createdBy" TEXT NOT NULL, "approvedBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "sales_quotes_pkey" PRIMARY KEY ("id"));
CREATE TABLE "msa_agreements" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "signatureDate" TIMESTAMP(3), "expiryDate" TIMESTAMP(3), "governingLaw" TEXT, "renewalTerms" JSONB, "documentUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "msa_agreements_pkey" PRIMARY KEY ("id"));

CREATE TABLE "qbr_decks" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "periodStart" TIMESTAMP(3) NOT NULL, "periodEnd" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "html" TEXT, "notes" TEXT, "pdfUrl" TEXT, "pptxUrl" TEXT, "nextQbrAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "qbr_decks_pkey" PRIMARY KEY ("id"));
CREATE TABLE "qbr_templates" ("id" TEXT NOT NULL, "segment" TEXT NOT NULL, "html" TEXT NOT NULL, "css" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "qbr_templates_pkey" PRIMARY KEY ("id"));
CREATE TABLE "sales_deals" ("id" TEXT NOT NULL, "tenantId" TEXT, "hubspotDealId" TEXT, "name" TEXT NOT NULL, "stage" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL DEFAULT 0, "probability" DECIMAL(5,2) NOT NULL DEFAULT 0, "closeDate" TIMESTAMP(3), "ownerEmail" TEXT, "payload" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "sales_deals_pkey" PRIMARY KEY ("id"));
CREATE TABLE "trial_activations" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "score" INTEGER NOT NULL DEFAULT 0, "firstShipmentCreated" BOOLEAN NOT NULL DEFAULT false, "teamInvited" BOOLEAN NOT NULL DEFAULT false, "paymentMethodConnected" BOOLEAN NOT NULL DEFAULT false, "webhookConfigured" BOOLEAN NOT NULL DEFAULT false, "customDomainSet" BOOLEAN NOT NULL DEFAULT false, "interventionStatus" TEXT NOT NULL DEFAULT 'NONE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "trial_activations_pkey" PRIMARY KEY ("id"));
CREATE TABLE "trial_extension_requests" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "requestedDays" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "requestedBy" TEXT, "approvedBy" TEXT, "reason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "trial_extension_requests_pkey" PRIMARY KEY ("id"));
CREATE TABLE "demo_environments" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "template" TEXT NOT NULL, "shareTokenHash" TEXT, "expiresAt" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdBy" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "demo_environments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "sales_handoffs" ("id" TEXT NOT NULL, "dealId" TEXT, "tenantId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING_SALES', "document" JSONB NOT NULL, "assignedCsmId" TEXT, "acceptedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "sales_handoffs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "marketing_attributions" ("id" TEXT NOT NULL, "tenantId" TEXT, "periodStart" TIMESTAMP(3) NOT NULL, "periodEnd" TIMESTAMP(3) NOT NULL, "source" TEXT NOT NULL, "campaign" TEXT, "landingPage" TEXT, "weight" DECIMAL(8,4) NOT NULL, "revenue" DECIMAL(12,2) NOT NULL DEFAULT 0, "payload" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "marketing_attributions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "pricing_experiments" ("id" TEXT NOT NULL, "vendorExperimentId" TEXT, "name" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "variants" JSONB NOT NULL, "metrics" JSONB, "startedAt" TIMESTAMP(3), "endedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "pricing_experiments_pkey" PRIMARY KEY ("id"));

CREATE TABLE "partners" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "tier" TEXT NOT NULL DEFAULT 'BRONZE', "status" TEXT NOT NULL DEFAULT 'ACTIVE', "commissionConfig" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "partners_pkey" PRIMARY KEY ("id"));
CREATE TABLE "partner_applications" ("id" TEXT NOT NULL, "partnerId" TEXT, "applicantEmail" TEXT NOT NULL, "companyName" TEXT NOT NULL, "type" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "payload" JSONB, "decidedBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "partner_applications_pkey" PRIMARY KEY ("id"));
CREATE TABLE "partner_deal_registrations" ("id" TEXT NOT NULL, "partnerId" TEXT NOT NULL, "leadEmail" TEXT NOT NULL, "companyName" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'REGISTERED', "lockedUntil" TIMESTAMP(3) NOT NULL, "dealId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "partner_deal_registrations_pkey" PRIMARY KEY ("id"));
CREATE TABLE "commission_ledger" ("id" TEXT NOT NULL, "partnerId" TEXT NOT NULL, "tenantId" TEXT, "dealId" TEXT, "amount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'GBP', "status" TEXT NOT NULL DEFAULT 'EARNED', "period" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "commission_ledger_pkey" PRIMARY KEY ("id"));
CREATE TABLE "commission_payouts" ("id" TEXT NOT NULL, "partnerId" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'GBP', "status" TEXT NOT NULL DEFAULT 'PENDING', "approvedByFinance" TEXT, "approvedByCfo" TEXT, "stripeTransferId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "commission_payouts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "commission_disputes" ("id" TEXT NOT NULL, "partnerId" TEXT NOT NULL, "payoutId" TEXT, "message" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "resolvedBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "commission_disputes_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "incident_records_vendorId_key" ON "incident_records"("vendorId");
CREATE UNIQUE INDEX "incident_tenant_impacts_incidentId_tenantId_key" ON "incident_tenant_impacts"("incidentId", "tenantId");
CREATE UNIQUE INDEX "incident_runbooks_slug_key" ON "incident_runbooks"("slug");
CREATE UNIQUE INDEX "support_vendor_tickets_vendor_vendorId_key" ON "support_vendor_tickets"("vendor", "vendorId");
CREATE UNIQUE INDEX "jit_access_approvals_requestId_approverPlatformUserId_key" ON "jit_access_approvals"("requestId", "approverPlatformUserId");
CREATE UNIQUE INDEX "secret_credentials_dopplerId_key" ON "secret_credentials"("dopplerId");
CREATE UNIQUE INDEX "ip_blocks_ipAddress_key" ON "ip_blocks"("ipAddress");
CREATE UNIQUE INDEX "kyc_reviews_inquiryId_key" ON "kyc_reviews"("inquiryId");
CREATE UNIQUE INDEX "integration_provider_statuses_provider_key" ON "integration_provider_statuses"("provider");
CREATE UNIQUE INDEX "tax_registrations_region_taxId_key" ON "tax_registrations"("region", "taxId");
CREATE UNIQUE INDEX "sales_quotes_quoteNumber_key" ON "sales_quotes"("quoteNumber");
CREATE UNIQUE INDEX "qbr_templates_segment_key" ON "qbr_templates"("segment");
CREATE UNIQUE INDEX "sales_deals_hubspotDealId_key" ON "sales_deals"("hubspotDealId");
CREATE UNIQUE INDEX "trial_activations_tenantId_key" ON "trial_activations"("tenantId");
CREATE UNIQUE INDEX "demo_environments_tenantId_key" ON "demo_environments"("tenantId");
CREATE UNIQUE INDEX "pricing_experiments_vendorExperimentId_key" ON "pricing_experiments"("vendorExperimentId");
CREATE UNIQUE INDEX "partner_deal_registrations_leadEmail_key" ON "partner_deal_registrations"("leadEmail");

CREATE INDEX "dunning_events_tenantId_createdAt_idx" ON "dunning_events"("tenantId", "createdAt");
CREATE INDEX "save_offers_tenantId_idx" ON "save_offers"("tenantId");
CREATE INDEX "incident_records_status_createdAt_idx" ON "incident_records"("status", "createdAt");
CREATE INDEX "incident_tenant_impacts_tenantId_createdAt_idx" ON "incident_tenant_impacts"("tenantId", "createdAt");
CREATE INDEX "tenant_health_scores_tenantId_computedAt_idx" ON "tenant_health_scores"("tenantId", "computedAt");
CREATE INDEX "jit_access_requests_requesterPlatformUserId_status_expiresAt_idx" ON "jit_access_requests"("requesterPlatformUserId", "status", "expiresAt");
CREATE INDEX "legal_holds_tenantId_status_idx" ON "legal_holds"("tenantId", "status");
CREATE INDEX "fraud_signals_tenantId_status_idx" ON "fraud_signals"("tenantId", "status");
CREATE INDEX "security_anomalies_status_createdAt_idx" ON "security_anomalies"("status", "createdAt");
CREATE INDEX "custom_contracts_tenantId_status_idx" ON "custom_contracts"("tenantId", "status");
CREATE INDEX "sales_deals_stage_closeDate_idx" ON "sales_deals"("stage", "closeDate");
CREATE INDEX "commission_payouts_partnerId_status_idx" ON "commission_payouts"("partnerId", "status");

ALTER TABLE "dunning_steps" ADD CONSTRAINT "dunning_steps_sequenceId_fkey" FOREIGN KEY ("sequenceId") REFERENCES "dunning_sequences"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "incident_tenant_impacts" ADD CONSTRAINT "incident_tenant_impacts_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "incident_records"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cs_playbook_runs" ADD CONSTRAINT "cs_playbook_runs_playbookId_fkey" FOREIGN KEY ("playbookId") REFERENCES "cs_playbooks"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "jit_access_approvals" ADD CONSTRAINT "jit_access_approvals_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "jit_access_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "dsar_transitions" ADD CONSTRAINT "dsar_transitions_dsarId_fkey" FOREIGN KEY ("dsarId") REFERENCES "dsar_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "secret_access_logs" ADD CONSTRAINT "secret_access_logs_secretId_fkey" FOREIGN KEY ("secretId") REFERENCES "secret_credentials"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pricing_overrides" ADD CONSTRAINT "pricing_overrides_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "custom_contracts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "contract_approvals" ADD CONSTRAINT "contract_approvals_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "custom_contracts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "partner_applications" ADD CONSTRAINT "partner_applications_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "partners"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "partner_deal_registrations" ADD CONSTRAINT "partner_deal_registrations_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "partners"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "commission_ledger" ADD CONSTRAINT "commission_ledger_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "partners"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "commission_payouts" ADD CONSTRAINT "commission_payouts_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "partners"("id") ON DELETE CASCADE ON UPDATE CASCADE;
