export const EMAIL_TEMPLATES = {
  booking_confirmed: 'booking_confirmed',
  shipment_picked_up: 'shipment_picked_up',
  out_for_delivery: 'out_for_delivery',
  delivered: 'delivered',
  failed_delivery: 'failed_delivery',
  shipment_exception: 'shipment_exception',
  invoice_sent: 'invoice_sent',
  invoice_overdue: 'invoice_overdue',
  payment_received: 'payment_received',
  return_approved: 'return_approved',
  return_received: 'return_received',
  return_refunded: 'return_refunded',
  ticket_created: 'ticket_created',
  ticket_reply_from_staff: 'ticket_reply_from_staff',
  ticket_reply_from_customer: 'ticket_reply_from_customer',
  ticket_resolved: 'ticket_resolved',
  password_reset: 'password_reset',
  staff_invite: 'staff_invite',
  trial_expiring: 'trial_expiring',
  usage_warning_80: 'usage_warning_80',
  usage_limit_reached: 'usage_limit_reached',
  ops_new_shipment: 'ops_new_shipment',
  trial_expiry: 'trial_expiry'
} as const;
